### ISSUE TITLE
CUDA out of memory if the -image_size is 800px

### ISSUE THREAD

**Issue by 3dimka** [genekogan/neural-style-pt#4]
It looks like the model eats a lot of space on nvidia, so increasing the image size causes out of memory error.

RuntimeError: CUDA out of memory. Tried to allocate 352.00 MiB (GPU 0; 8.00 GiB total capacity; 6.31 GiB already allocated; 351.56 MiB free; 6.35 GiB reserved in total by PyTorch)

Capturing style target 1
Traceback (most recent call last):
  File "neural_style.py", line 601, in <module>
    main()
  File "neural_style.py", line 238, in main
    net(style_images_caffe[i])
  File "C:\Users\3dimka\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\3dimka\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\3dimka\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\3dimka\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\3dimka\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,

**Comment by genekogan** [comment]
Try enabling cudnn `-backend cudnn` and that should give you back some memory. But yes, it does eat a lot of memory and I would not expect much more than 800px with 8GB VRAM.
