### ISSUE TITLE
Histogram Loss for higher Pytorch version

### ISSUE THREAD

**Issue by xchhuang** [genekogan/neural-style-pt#5]
Hi @genekogan ,

I am wonder if you have tried the histogram loss with newer Pytorch version. Currently I am using Python 3.7.9 and Pytorch 1.6.0 on Windows 10, but got the following errors:
```
neural_style.py:98: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(len(content_seg_list) == len(style_image_list), \
neural_style.py:115: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(len(style_seg_list) == len(style_image_list), \
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf2\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "D:\Anaconda3\envs\tf2\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "neural_style.py", line 63, in <module>
    cpp = torch.utils.cpp_extension.load(name="histogram_cpp", sources=["histogram.cpp", "histogram.cu"])
  File "D:\Anaconda3\envs\tf2\lib\site-packages\torch\utils\cpp_extension.py", line 974, in load
    keep_intermediates=keep_intermediates)
  File "D:\Anaconda3\envs\tf2\lib\site-packages\torch\utils\cpp_extension.py", line 1179, in _jit_compile
    with_cuda=with_cuda)
  File "D:\Anaconda3\envs\tf2\lib\site-packages\torch\utils\cpp_extension.py", line 1279, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "D:\Anaconda3\envs\tf2\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error building extension 'histogram_cpp': [1/3] cl /showIncludes -DTORCH_EXTENSION_NAME=histogram_cpp -DTORCH_API_INCLUDE_EXTENSION_H -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include -ID:\Anaconda3\envs\tf2\lib\sit
e-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"
...
[2/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_witho
ut_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xco
mpiler /MD -DTORCH_EXTENSION_NAME=histogram_cpp -DTORCH_API_INCLUDE_EXTENSION_H -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\
tf2\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -ID:\Anaconda3\envs\tf2\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA
_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 
FAILED: histogram.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll
_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler
 /MD -DTORCH_EXTENSION_NAME=histogram_cpp -DTORCH_API_INCLUDE_EXTENSION_H -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\tf2\li
b\site-packages\torch\include\TH -ID:\Anaconda3\envs\tf2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -ID:\Anaconda3\envs\tf2\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HA
LF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 ... -o histogram.cuda.o
D:/Anaconda3/envs/tf2/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

D:/Anaconda3/envs/tf2/lib/site-packages/torch/include\ATen/record_function.h(18): warning: modifier is ignored on an enum specifier

D:/Anaconda3/envs/tf2/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(483): error: a member with an in-class initializer must be const

D:/Anaconda3/envs/tf2/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(496): error: a member with an in-class initializer must be const

D:/Anaconda3/envs/tf2/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(510): error: a member with an in-class initializer must be const

D:/Anaconda3/envs/tf2/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(523): error: a member with an in-class initializer must be const

D:/Anaconda3/envs/tf2/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(97): warning: modifier is ignored on an enum specifier

D:/Anaconda3/envs/tf2/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(126): warning: modifier is ignored on an enum specifier

4 errors detected in the compilation of ...
histogram.cu
ninja: build stopped: subcommand failed.
```

Do you have any idea for this issue? Thanks in advance!

**Comment by genekogan** [comment]
I've had problems compiling ninja on latest pytorch, it looks like maybe the error is connected to that. Honestly, I didn't see a ton of improvement with using histogram loss (YMMV) so if you're struggling to compile it, I wouldn't necessarily put much energy into it. Also, I do this all on Linux, no idea about Windows...

**Comment by xchhuang** [comment]
> I've had problems compiling ninja on latest pytorch, it looks like maybe the error is connected to that. Honestly, I didn't see a ton of improvement with using histogram loss (YMMV) so if you're struggling to compile it, I wouldn't necessarily put much energy into it. Also, I do this all on Linux, no idea about Windows...

I see. I also tried on Linux, but had the same issue. 
Thanks!
